version: '2'
services:
  ecs:
    environment:
      INSTANCE_IP: ${INSTANCE_IP}
      ECS_CLUSTER: {{ name }}
      {%- if ECS_ENGINE_AUTH_DATA is defined %}
      ECS_ENGINE_AUTH_DATA: '{{ ECS_ENGINE_AUTH_DATA }}'
      {%- endif %}
      {%- if ECS_ENGINE_AUTH_DATA is defined %}
      ECS_ENGINE_AUTH_TYPE: {{ ECS_ENGINE_AUTH_TYPE }}
      {%- endif %}
    {%- if logging is defined %}
    logging:
      driver: {{ logging.driver }}
      options:
        {% for key, option in logging.options %}
        {{ key }}: {{ option }}
        {% endfor %}
    {% endif %}